### ISSUE TITLE
Interested on running the app

### ISSUE THREAD

**Issue by AndresDavidArcos** [RobJenks/gpt-codegen#20]
Hello,

I'm attempting to run the application, but it seems like the instructions provided are outdated. Could you please update them for running the Java application?

I followed the instructions, but encountered errors when pressing "update process" from the UI. The error message displayed was "Resource not found: /path/to/api-key". In the llm-generation-service app.properties file, I've set the token as token=apikey.txt.

Additionally, I attempted to pass it with -Dgptclient.type=mock, but encountered issues. After installing with mvn clean install, I executed the JAR located in the target directory of llm-generation-service.

It appears that I might be missing something or doing something incorrectly. Could you please provide more detailed instructions or clarify the steps needed to successfully run the application?

Thank you.

**Comment by RobJenks** [comment]
Hi Andres,

You're right - there have been some major changes to the library modules, we needed to bring the example service & documentation back up-to-date

I've just updated master and also published version [0.0.2](https://github.com/RobJenks/gpt-codegen/releases/tag/0.0.2) with these changes.  There are a few (minor) changes to the [setup instructions](https://github.com/RobJenks/gpt-codegen/blob/master/docs/README.md).  Give it a try and hopefully this should work for you now.
